apiVersion: v1
kind: Secret
metadata:
  name: credentials
  labels:
    app: app
    chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    release: '{{ .Release.Name }}'
    heritage: '{{ .Release.Service }}'
type: Opaque
data:
  twitchclient_id: {{ .Values.twitchclient_id | b64enc | replace "\"" "" }}
  twitchsecret: {{ .Values.twitchsecret | b64enc | replace "\"" "" }}
  bot_token: {{ .Values.bot_token | b64enc | replace "\"" "" }}
